### ISSUE TITLE
Keep restarting game

### ISSUE THREAD

**Issue by Ghostedexe** [thatskymod/Sky-CotL-Scripts#16]
I got the gxost.so file for canvas but it keeps restarting sky plz help

**Comment by thatskymod** [comment]
Good news! An update for {re}Hell with many bug fixes and improvements just came out. Try it out and let me know whether the issue persists:
[./Canvas/Libs/libgxost-1.1.1.so](https://github.com/thatskymod/Sky-CotL-Scripts/blob/main/Canvas/Libs/libgxost-1.1.1.so)

**Comment by thatskymod** [comment]
Hi @Ghostedexe, how are you?
Is this issue still relevant?

**Comment by thatskymod** [comment]
@Ghostedexe, do you still need assistance?

If simply updating libgxost doesn't help, you can try deleting everything related to Canvas, including Canvas itself. Then, give it a fresh start, downloading everything again and adding a mod one by one. This will allow you to identify which particular mod is causing the breakage to happen.

Let me know if you were able to solve it. This is your final reminder before the issue is marked inactive.

**Comment by thatskymod** [comment]
Due to the lack of activity on this issue and despite multiple attempts to reach out without receiving a response, this issue will now be closed.

However, please don't hesitate to open a new issue for any further questions or concerns in the future.

Thank you for your understanding.
