### ISSUE TITLE
New update issue

### ISSUE THREAD

**Issue by ghost** [thatskymod/Sky-CotL-Scripts#17]
Hi, I am an android user using Canvas. I am having an issue with autowax mod. I had 100 candles but, as soon as I used it I saw the number decrease down to 1. Today I used auto wax again but it only forged me 1.
Also, both crawl and spam honk no longer work with the new update.
Can you guys fix this?

**Comment by Ghostedexe** [comment]
> 

Auto honk is bandable, the system detects when you use auto honk and send a system report automatically

**Comment by thatskymod** [comment]
Hey! I'm sorry to hear that.

AutoWax unto itself does not withdraw candles unless instructed. Be sure to check and remove any unwanted people from "Heart trade config" (the first checkbox under "Run").

Or, did you perhaps buy something from the spirit shops? That could also have reduced your candle count.

About the spam honk in reHell: tgc has added a detection mechanism for frequent/loud honks and gets notified if you do it, so that cheat has been disabled for your own safety.

**Comment by Leah821** [comment]
Hi, i'm canvas android user. I was unable to use the collect WL option. When i check it, type the number of wl i want to collect in the box and press run, it just says this 
![Screenshot_20230212_030240_Canvas](https://user-images.githubusercontent.com/125159440/218282062-bd9ae787-56cb-4fff-bc3c-6daa1221b6ad.jpg)

Am i using the function wrong like missing something or is there some peoblem with it?

**Comment by Ghostedexe** [comment]
Hey uh your doing it wrong there actually a full word.txt for u to paste

**Comment by thatskymod** [comment]
@Leah821, that's not how it works. The text box is for you to specify which WL to collect (a comma-separated list of names)

You can get them here:
[./Canvas/Misc/220_wing_code_Sky.txt](https://raw.githubusercontent.com/thatskymod/Sky-CotL-Scripts/main/Canvas/Misc/220_wing_code_Sky.txt) 

**Method 1** - Select & copy the list and `Paste` it from clipboard
**Method 2** - Save the .txt file (look for a download button in your browser), and load that file into Autowax

This should get you 220 wings the next time you log into Sky.

**Comment by thatskymod** [comment]
Closing issue as invalid, find explanation in [comment](https://github.com/thatskymod/Sky-CotL-Scripts/issues/17#issuecomment-1419150767)
