### ISSUE TITLE
Server Error at the log in screen of Canvas

### ISSUE THREAD

**Issue by SomebuddyElse7** [thatskymod/Sky-CotL-Scripts#31]
#/Description:
When i start play at the log in screen it says there is a Server error and it keeps popping up over

Expected behavior:
 I tried to  clear data both canvas and Original Sky game and tried to log in from another account but the server error still pops up
 
Screenshots:
![Screenshot_2023-05-16-09-22-46-041_git artdeell skymodloader](https://github.com/thatskymod/Sky-CotL-Scripts/assets/130241761/8f83e5e4-88d8-48c9-a914-29c292f1fa96)

**Machine (please complete the following information):**
 - Device: Redmi Note 9 pro max
 - OS:  Android 12
 - App(s) affected:Canvas, Mod manager
 - Version: 1.3.6

Additional context:
 I also removed the libs added in the mod manager and uninstall and reinstalled the canvas but when i opened it again the libs are shown as added again

**Comment by Skybish23** [comment]
Hope is resolved soon

**Comment by thatskymod** [comment]
Known issue, awaiting a fix from Canvas developers.

In the meantime, one possible workaround is to rely on alternate login methods. If you are already a Nintendo user, skip to step 7.

1. Log in to official Sky.
2. Tap the cog wheel icon in the upper right.
3. Select "Account".
4. Choose "Nintendo".
5. Follow the on-screen instructions to link your Nintendo account. If you do not have a Nintendo account, you can register for one - it's free and does not require a console.
6. Once linked, exit Sky.
7. Launch Canvas and proceed with Nintendo as your login method.

I understand that this may not be the most convenient solution, but your patience and understanding is greatly appreciated while the issue is being worked on.

**Comment by SomebuddyElse7** [comment]
Thanks it works on a Nintendo account,hope they fix the Authentication process for Google Account soon.
