### ISSUE TITLE
#Ask!! LibRoman

### ISSUE THREAD

**Issue by Lim99fox** [thatskymod/Sky-CotL-Scripts#8]
what is libroman for? and how to use it?

**Comment by thatskymod** [comment]
Hello, libRoman is for [Sky Beta](https://play.google.com/store/apps/details?id=com.tgc.sky.android.test.gold) only. To use it, you must first enable "Sky Beta support" in Mod Manager.
@Lim99fox

**Comment by Lim99fox** [comment]
but what appears is only a letter, and nothing happens

**Comment by thatskymod** [comment]
Okay, that means it refused to initialize, likely due to one of the following:

- Package mismatch (check Mod Manager & make sure you really enabled Sky Beta support)
- Sky Beta version mismatch (check for updates or manually upgrade to 0.20.0 208796, if not already)
- libRoman version mismatch (1.1.4 is latest)

Additionally:
- libRoman**Dev** is only needed to play on the dev server, uninstall it to access Beta normally

I'm looking forward to writing a wiki and documenting the libs in detail over the next few days, so it'll be easier to navigate, troubleshoot and find what you're looking for.

@Lim99fox

**Comment by Lim99fox** [comment]
thank you very much, you are the best bro
